# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed5f070c8160f60b729322e6fd764c6961a3438551973700c8ae4d8ceb12a125b1e7952f71f344287a08f788dacfdac7d8a1c536e340d195dca32714c36b54ec

test:
  secret_key_base: 7e5d1e7ef54868f350b27234d614b3ad75a6f6c66c4851871a3f2ff4b049460e4fd56fb682fde4924518152c739fe47e439be7bb80e1774f9a4b68f2aba7839c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
